version: '3'

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  ruby_rabbitmq_publisher:
    build: .
    container_name: ruby_rabbitmq_publisher
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672


  ruby_rabbitmq_consumer:
    build: .
    container_name: ruby_rabbitmq_consumer
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
